### PR TITLE
bugfix for code range

### PR DESCRIPTION
**Pull request by hy05190134**
when not think of the code range, it will match the wrong item because the key is uint64 from bfrange or bfchar, it really happen in my case

### CODE REVIEW

**Comment by gunnsth** [comment]
Can you please describe the rationale a little bit?
Just going through this, looks like for example, if we have
a codespacerange:
<00> <80>
<8140> <9FFC>

Then the first case is 0x00 - 0x80, where len("80") = 2
so the codespan is
cmap.codeSpan = 0 | 2^2 = 4

why 2^power? and not 16? (hex). Would seem with 2 bytes the maximum could be 0xFF and 0xFFFF with 4 bytes.

and the second case is 0x8140 - 0x9FFC where len("9FFC") = 4
so here cmap.codeSpan = 4 | 2^4 = 4 | 16 = 20
...

Then in the unicode conversion, a requirement is:
cmap.codeSpan & 2^(j+1) where j+1 is the number of bytes per code

Why is it not enough that the code is in the codeMap?  or check that it is within the specified codespaces? A test case/example would be helpful.

**Comment by hy05190134** [comment]
if you don't use the info of bfcoderange (that is mean how many bytes to CID), it will cause one byte to map to unicode(because the value calculated from one byte also exist in the codemap), but actually one byte is not fit the len of CID(the real CID is two)

**Comment by hy05190134** [comment]
@gunnsth

**Comment by hy05190134** [comment]
[xxx.pdf](https://github.com/unidoc/unidoc/files/2043206/xxx.pdf)
it will cause the problem when extract text from this file(see last page of character "FI", actually it is just one character)

**Comment by gunnsth** [comment]
Thanks, you are correct.  The codeMap map[uint64]string has lost the information about the number of bytes, affecting codes starting with 0 bytes.

I feel like the codeSpan solution, although fixes the case here, is not obvious.  (Would be more obvious just to compare the number of bytes).  But also, may not work when working with code spaces of non-uniform lengths, e.g.
<00> <80>
<8140> <9FFC>
i.e. one with 0x00 - 0x80, and second 0x8140 - 0x9FFC

A more generic solution would be to include the number of bytes in the codeMap. e.g.
rather than 
codeMap map[uint64]string
use
codeMap map[int][uint64]string

where the map is a [number of bytes][code] -> rune.   This in the case where number of bytes is 1, then there will be no match for <80>.  This solution should be pretty efficient.

What do you think?  Probably also include a test case for this scenario in our test suite.

**Comment by hy05190134** [comment]
the solution expand the map do will fix the bug, but it will expand the memory of use. Since the codespace will not overlap, I think using codeSpan is enough to resolve

**Comment by gunnsth** [comment]
The more generic handling has been implemented in
https://github.com/unidoc/unidoc/commit/a7abcd01608a6ce352b901216d3d38e6e7c9a029

The approach has minimal overhead and allows more complex CMaps to be handled, which could be especially useful if needs to be extended beyond ToUnicode CMaps.

Would appreciate if you can check if this resolves the problem.  I have added test cases for this also.

**Comment by hy05190134** [comment]
@gunnsth , good, I have already test the pdf which is not correct before

**Comment by gunnsth** [comment]
@hy05190134 Good. If you have any more cases, please file more issues.  Both for bugs and missing features.  We could also extend our test cases. This is very useful. We can still improve a lot in this area and your contributions are very welcome.

Regarding your last point

> you should also use BaseEncoding info & preDefinedCmap to extract the test

Can you please elaborate?

Thanks.

**Pull request closed without merging**
